import os
from dotenv import load_dotenv
from crewai import Agent

# Load environment variables from .env file
load_dotenv()

# Ensure GROQ_API_KEY is available
if "GROQ_API_KEY" not in os.environ:
    raise ValueError("GROQ_API_KEY not found in environment variables. Please set it in your .env file.")

predictive_agent = Agent(
    role="Universal AI Inventory Data Analyst",
    goal="Adaptively read any shop's CSV data schema with pre-calculated system metrics, and predict top low-stock and high-trend items.",
    backstory="""
    You are an elite data scientist and supply chain AI. You have been trained to handle any arbitrary dataset 
    from any shop or e-commerce platform. You look at pre-calculated REORDER POINTS and SYSTEM PRIORITY to output exact lists.
    """,
    llm="groq/llama-3.3-70b-versatile",
    verbose=False
)

strategist_agent = Agent(
    role="Supply Chain Strategist",
    goal="Identify the Critical/High priority items from the Analyst's report and devise an emergency shipping or reorder plan.",
    backstory="""
    You are a veteran Supply Chain Director. Your job is to take the data flags generated by the Analyst 
    and provide actionable, cost-effective reorder suggestions (e.g. standard vs express shipping modes) 
    to prevent lost revenue.
    """,
    llm="groq/llama-3.3-70b-versatile",
    verbose=False
)
